### ISSUE TITLE
No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

### ISSUE THREAD

**Issue by Aiman-Jabaren** [Dene33/video_to_bvh#13]
When processing the uploaded video, I get:
Traceback (most recent call last):
  File "/content/hmr/csv_to_bvh.py", line 20, in <module>
    with open(fullpath, 'r', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

Blender quit
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f3c34c0e400 

What is the above supposed to mean and how can I fix it? how can I create the files and download them?

Thanks,

**Comment by youngheekim** [comment]
I get the same error with the movie that was used before. Then it worked fine. Is there anything changed? I checked the README file.

**Comment by Justinemmerich** [comment]
I have the same problem and still workin on my masterthesis with this nice project. Hope for a quick fix

**Comment by johnlinml** [comment]
I work around the problem by renaming my video to only with numbers

**Comment by johnlinml** [comment]
The missing of csv_joined.csv is due to joining function failed.

**Comment by AzizSant** [comment]
> I work around the problem by renaming my video to only with numbers

Thanks for sharing. I've tried to rename the video but I still got the same error. Do you mind sharing the exact video file name and format that worked out for you?

**Comment by johnlinml** [comment]
1.mp4 and 2.mp4. I found that csv files were created but 
"  all_files.sort(key=lambda x: int(x.split('/')[-1].split('.')[0]))" in     join_csv()
 failed.

**Comment by eve000017** [comment]
File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config.  Description from first occurrence: directory to write logfiles into
Done
Read blend: /content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.blend
[bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
Traceback (most recent call last):
  File "/content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.py", line 20, in <module>
    with open(fullpath, 'r', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

Blender quit
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f3a62c0e400 

the error come even i change the name of video...
anyone can help?

**Comment by AzizSant** [comment]
> File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 430, in **setitem**
> raise _exceptions.DuplicateFlagError.from_flag(name, self)
> absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config. Description from first occurrence: directory to write logfiles into
> Done
> Read blend: /content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.blend
> [bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
> Traceback (most recent call last):
> File "/content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.py", line 20, in
> with open(fullpath, 'r', newline='') as csvfile:
> FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'
> 
> Blender quit
> src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f3a62c0e400
> 
> the error come even i change the name of video...
> anyone can help?

Have you tried this: https://github.com/Dene33/video_to_bvh/issues/12#issuecomment-504075727

**Comment by eve000017** [comment]
> > File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 430, in **setitem**
> > raise _exceptions.DuplicateFlagError.from_flag(name, self)
> > absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config. Description from first occurrence: directory to write logfiles into
> > Done
> > Read blend: /content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.blend
> > [bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
> > Traceback (most recent call last):
> > File "/content/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/sample_videos/keras_Realtime_Multi-Person_Pose_Estimation/hmr/csv_to_bvh.py", line 20, in
> > with open(fullpath, 'r', newline='') as csvfile:
> > FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'
> > Blender quit
> > src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f3a62c0e400
> > the error come even i change the name of video...
> > anyone can help?
> 
> Have you tried this: [#12 (comment)](https://github.com/Dene33/video_to_bvh/issues/12#issuecomment-504075727)

i tried and get another error.

2019-09-19 12:41:27.908203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3454 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
W0919 12:41:27.909207 140704186623872 deprecation_wrapper.py:119] From /content/hmr/src/RunModel.py:42: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

Traceback (most recent call last):
  File "hmr/demo.py", line 211, in <module>
    main(config.img_path, config.json_path)
  File "hmr/demo.py", line 125, in main
    model = RunModel(config, sess=sess)
  File "/content/hmr/src/RunModel.py", line 62, in __init__
    self.build_test_model_ief()
  File "/content/hmr/src/RunModel.py", line 82, in build_test_model_ief
    reuse=False)
  File "/content/hmr/src/models.py", line 40, in Encoder_resnet
    with tf.name_scope("Encoder_resnet", [x]):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 6450, in __init__
    "pass this into the `values` kwarg." % type(default_name))
TypeError: `default_name` type (<type 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.
Done
Read blend: /content/hmr/csv_to_bvh.blend
[bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
Traceback (most recent call last):
  File "/content/hmr/csv_to_bvh.py", line 20, in <module>
    with open(fullpath, 'r', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

Blender quit
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7fbcf740e400

**Comment by eve000017** [comment]
https://github.com/akanazawa/hmr/issues/69#issuecomment-503765527

solved the "TypeError: default_name type (<type 'list'>) is not a string type. You likely meant to pass this into the values kwarg." issue by the link above.. 

Thank you.

**Comment by timbuktu031** [comment]
same error.
I can't download bvh file

**Comment by alshami52** [comment]
Still have a problem with this,
No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'
any help?!
