### ISSUE TITLE
"Process the video" error

### ISSUE THREAD

**Issue by LGGGGGG** [Dene33/video_to_bvh#24]
When processing,I get:
Traceback (most recent call last):
  File "hmr/demo.py", line 27, in <module>
    import tensorflow as tf
  File "/tensorflow-1.15.0/python3.6/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/tensorflow-1.15.0/python3.6/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/tensorflow-1.15.0/python3.6/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dynamic module does not define init function (init_pywrap_tensorflow_internal)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

I cheched the README file many times but still get this error.Maybe the incorrect tensflow verson cause this problem?

**Comment by LGGGGGG** [comment]
> 
> 
> When processing,I get:
> Traceback (most recent call last):
> File "hmr/demo.py", line 27, in
> import tensorflow as tf
> File "/tensorflow-1.15.0/python3.6/tensorflow/**init**.py", line 99, in
> from tensorflow_core import *
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/**init**.py", line 28, in
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "/tensorflow-1.15.0/python3.6/tensorflow/**init**.py", line 50, in **getattr**
> module = self._load()
> File "/tensorflow-1.15.0/python3.6/tensorflow/**init**.py", line 44, in _load
> module = _importlib.import_module(self.**name**)
> File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
> **import**(name)
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/**init**.py", line 49, in
> from tensorflow.python import pywrap_tensorflow
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow.py", line 74, in
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> ImportError: dynamic module does not define init function (init_pywrap_tensorflow_internal)
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.
> 
> I cheched the README file many times but still get this error.Maybe the incorrect tensflow verson cause this problem?

I fixed all problems I've met;
1.tensorflow version
1.1 we should run `%tensorflow_version 1.x` in initial step
1.2 before you run upload vedio module, add  `sys.path.insert(0,'/tensorflow-1.15.2/python2.7')` in hmr/demo.py
2.hmr error
2.1before you run upload vedio module,change all `log_dir` to `logging_dir` in hmr/src/config.py
2.2before you run upload vedio module,refer to
> Using the TensorFlow documentation for [tf.name_scope](https://www.tensorflow.org/api_docs/python/tf/name_scope), I resolved the issue by prepending `[x]` with `values=`. That is change `with tf.name_scope("Encoder_resnet", [x]):` to `with tf.name_scope("Encoder_resnet", values=[x]):`. This error also occurs in a few places over in `batch_lbs.py` which I fixed in the same way.
