### ISSUE TITLE
ImportError: No module named contrib.slim

### ISSUE THREAD

**Issue by HamzaKhalloufi** [Dene33/video_to_bvh#32]
**I get this error message after succefully getting json files** 
**I tried several tensorflow versions but I still get the same error**
Processing How001
Traceback (most recent call last):
  File "hmr/demo.py", line 33, in <module>
    from src.RunModel import RunModel
  File "/content/hmr/src/RunModel.py", line 13, in <module>
    from .models import get_encoder_fn_separate
  File "/content/hmr/src/models.py", line 19, in <module>
    import tensorflow.contrib.slim as slim
ImportError: No module named contrib.slim

**Comment by andreixxi** [comment]
@HamzaKhalloufi try this: https://github.com/google-research/tf-slim<br>
I used `pip install --upgrade tf_slim` and then in another cell this: `import tf_slim as slim`. also comment the import in the script, it did the trick for me.

**Comment by tuanfeng** [comment]
the problem is with contrib, not slim. use tensorflow 1.15 will solve the problem.

**Comment by nimishmagre** [comment]
> the problem is with contrib, not slim. use tensorflow 1.15 will solve the problem.

tried that but now I'm getting new errors like 
ImportError: Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dynamic module does not define init function (init_pywrap_tensorflow_internal)

**Comment by galaktyk** [comment]
It because colab now use tensorflow2 as default and the 'contrib' module is not available anymore.
So I've made a Tensorflow lite-version of this repo here -->
https://github.com/galaktyk/mocap-hmr-tflite
