### ISSUE TITLE
Process the video

### ISSUE THREAD

**Issue by sidul001** [Dene33/video_to_bvh#36]
**So I have successfully ran 2d pose estimation and have gotten json  outputs. 
But I am running into this issue with 3D pose estimation function (bash hmr/3dpose_estimate.sh). 
Please help!** 

Traceback (most recent call last):
  File "hmr/demo.py", line 32, in <module>
    import src.config
  File "/content/hmr/src/config.py", line 59, in <module>
    flags.DEFINE_string('log_dir', 'logs', 'Where to save training models')
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 82, in DEFINE
    flag_values, module_name)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 104, in DEFINE_flag
    fv[flag.name] = flag
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 430, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'log_dir' is defined twice. First from absl.logging, Second from src.config.  Description from first occurrence: directory to write logfiles into
Done
Read blend: /content/hmr/csv_to_bvh.blend
[bpy.data.objects['Ankle.R'], bpy.data.objects['Knee.R'], bpy.data.objects['Hip.R'], bpy.data.objects['Hip.L'], bpy.data.objects['Knee.L'], bpy.data.objects['Ankle.L'], bpy.data.objects['Wrist.R'], bpy.data.objects['Elbow.R'], bpy.data.objects['Shoulder.R'], bpy.data.objects['Shoulder.L'], bpy.data.objects['Elbow.L'], bpy.data.objects['Wrist.L'], bpy.data.objects['Neck'], bpy.data.objects['Head'], bpy.data.objects['Nose'], bpy.data.objects['Eye.L'], bpy.data.objects['Eye.R'], bpy.data.objects['Ear.L'], bpy.data.objects['Ear.R'], bpy.data.objects['Hip.Center']]
Traceback (most recent call last):
  File "/content/hmr/csv_to_bvh.py", line 20, in <module>
    with open(fullpath, 'r', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'hmr/output/csv_joined/csv_joined.csv'

Blender quit
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f1e9680e400

**Comment by adityab05** [comment]
Could you resolve this issue? If yes could you please share how? I am facing the same issue right now.
